allowances/contracts/AlowanceModule.sol, allowances/test/allowanceManagement.js
Reports:
1. `removeDelegate` doesn't update `delegatesStart` which will break the delegate linked list.
2. `removeDelegate` doesn't functionally remove the delegates, they can still have allowances and they can't be added back in with `addDelegate`. `removeDelegate` only affects the output of `getDelegates`
3. `ecrecover` returns 0 on failure, which will lead to this check passing, this isn't a security vulnerability if there are no allowances for the `0` address, but is still unexpected. https://github.com/gnosis/safe-modules/blob/master/allowances/contracts/AlowanceModule.sol#L241
Changes:
- Added tests for all reports
- Enforce that allowances cannot be set for the 0 address
- Enforce that delegates or their derived index cannot be the 0 address
- Enforce that the contract reverts on …
=> Fix audit comments

recurring_transfers/package.json
Fixes issue: #28 
It looks like `eth-lightwallet@^3.0.1`
depends on: 
`bitcore-lib "^0.15.0"` and
`bitcore-mnemonic "^1.5.0"`
While `bitcore-mnemonic "^1.5.0"` depends on:
`bitcore-lib "^0.16.0 `
This conflict can be resolved with this PR. Either version 0.15.0 or 0.16.0 can be used as resolutions.
=> Version conflict with bitcore-lib 

allowances/migrations/1_deploy_allowance_modules.js, allowances/truffle-config.js
This PR:
- fixes a bug where any string set as `USE_SAFE_SINGLETON_FACTORY` would eval as a truthy value
- add configuration for celo network
=> Do not allow implicit casting of `USE_SAFE_SINGLETON_FACTORY` variable, add celo config

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/ci_4337.yml, 4337/README.md, 4337/package.json
- Add sequence diagram for setup flow
- Add example code for `initCode` createion
- Fix typos
=> Document setup flow

4337/.env.sample, 4337/contracts/EIP4337Module.sol, 4337/contracts/interfaces/Safe.sol, 4337/contracts/test/SafeMock.sol, 4337/contracts/test/TestEntryPoint.sol, 4337/contracts/test/TestReverter.sol, 4337/src/utils/safe.ts, 4337/src/utils/userOp.ts, 4337/test/eip4337/EIP4337ModuleExisting.spec.ts, 4337/test/eip4337/EIP4337ModuleNew.spec.ts, 4337/test/eip4337/EIP4337Safe.spec.ts
This PR:
- Extracts the execution function of a user operation into a separate function on the module (previously, the entrypoint would directly call `execTransactionFromModule` and had to be enabled as a module as well
- This was done to require `success` and revert on failing transactions to enable a proper gas estimation
This PR is a prototype only at the moment, and the goal is to seek the team's feedback on the approach.
=> ERC4337 module feature: Extract execution to a separate function and require success in the internal call

4337/.env.sample, 4337/contracts/test/TestToken.sol, 4337/hardhat.config.ts, 4337/package-lock.json, 4337/package.json, 4337/scripts/runOp.ts, 4337/src/deploy/deploy_eip4337.ts, 4337/src/deploy/deploy_test.ts, 4337/src/utils/execution.ts, 4337/tsconfig.json
This PR:
- Adds an optional ERC20 transfer execution in the `runOp` script to test contract calls
- Executes if the environment variable for the token address is set. The pre-requisite is Safe should own at least one token. It will transfer precisely 1.
- The token name is coming from https://www.behindthename.com/random/random.php?gender=both&number=2&sets=1&surname=&all=yes
Notes:
- I had to bump the compiler version to `0.8.20` because of openzeppelin's token requirements and change the default EVM target from `Shanghai` to `London`, because Mumbai didn't support the `PUSH0` opcode added in `Shanghai`
- I also had to bump the target ES spec to `es2020` to use BigInts
=> Feature: Add an optional ERC20 transfer in the `runOp.ts` script to test contract calls

4337/README.md, 4337/hardhat.config.ts
This PR:
- Adjusts the compiler settings to use the latest `solc` compiler and document the settings
=> Feature: Adjust compiler settings and document optimizer usage

.github/CODEOWNERS
This PR adds a `CODEOWNERS` file. The motivation for adding this [is](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners):
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.
Here, we setup the `safe-protocol` team to be the code owner for all files in this repository, so PRs that are created to this repo will automatically request a review from that team.
=> Define CODEOWNERS Files

4337/.solcover.js
As test coverage for test contracts is not really important, we should skip it in the coverage report (so that it only reflects test coverage for the core contracts of the repo).
=> Skip Coverage for Test Contracts

README.md
=> Include 4337 Module Link in Project README

4337/.prettierrc, 4337/contracts/EIP4337Module.sol, 4337/contracts/interfaces/Safe.sol, 4337/contracts/test/SafeMock.sol, 4337/contracts/test/TestEntryPoint.sol, 4337/package.json
This PR applies a minor suggestion resulting from the audit where the `validateUserOp` parameter names (specifically for the required account fund transfer to the entrypoint) did not exactly match the name from the ERC.
Note that the test entrypoint was slightly adjusted to more closely model the behaviour of the [reference entrypoint](https://github.com/eth-infinitism/account-abstraction/blob/94cf025ef1c07b4b404ecd1c732266b378caaa92/contracts/core/EntryPoint.sol#L421-L427), where left-over user balances are considered when computing the  `missingAccountFunds` to pass into the `validateUserOp` call:
```solidity
uint256 missingAccountFunds = 0;
if (paymaster == address(0)) {
uint256 bal = balanceOf(sender);
missingAccountFunds = bal > requiredPrefund
? 0
: requiredPrefund - bal;
}
```
I …
=> Rename `requiredPrefund` to `missingAccountFunds`

4337/contracts/EIP4337Module.sol, 4337/contracts/test/TestEntryPoint.sol
This PR just renames `validationResult` to `validationData` to match the return variable name that is used in the specification.
=> Rename `validationResult` to `validationData`

4337/scripts/runOp.ts
This PR fixes the `runOp` script to use the `SUPPORTED_ENTRYPOINT` call instead of the deprecated `supportedEntrypoint` call.
I noticed this when testing changes to the module to see what is allowed in terms of storage access from bundlers.
=> Fix runOp Script For New Module ABI

4337/contracts/EIP4337Module.sol
This PR changes the validation result to use a constant instead of the `0` magic value to better document the intentions. It adds a comment explaining the (IMO not immediately intuitive) semantic of using validation data with `validUntil` set to 0 to indicate "valid until infinity and beyond".
=> Document Signature Validation Result

.github/workflows/cla.yml
Change the CLA bot to explicitly request the required permissions. This is done in accordance to the CLA bot [documentation](https://github.com/contributor-assistant/github-action#1-add-the-following-workflow-file-to-your-repository-in-this-pathgithubworkflowsclayml):
> ```
> # explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
> permissions:
>   actions: write
>   contents: write
>   pull-requests: write
>   statuses: write
> ```
=> Bump CLA action version, Explicitly Request Required PR Permission for CLA Bot

4337/contracts/EIP4337Module.sol
This PR trivially adds a comment justifying why we are ignoring the result of the prefund transaction, as it led to some confusion during the audit.
=> Add Comment Justifying Ignored Prefund Result

4337/contracts/Safe4337Module.sol, 4337/contracts/interfaces/Safe.sol, 4337/contracts/test/SafeMock.sol
This PR makes the 4337 Solidity code follow the standard naming convention where internal and private functions should be prefixed with `_`.
=> Follow Solidity Internal Function Naming Convention

4337/contracts/Safe4337Module.sol, 4337/contracts/test/SafeMock.sol, 4337/contracts/test/TestEntryPoint.sol, 4337/test/eip4337/EIP4337Module.spec.ts
Addresses another comment resulting from the module audit and verifies the constructor argument is not the `0` address to avoid accidental mistakes that may lead to invalid deployed contracts.
I noticed when deciding the exact revert message to use that there were many ways to spell "entry point" and slightly inconsistent capitalisation in existing messages, so I corrected those as well.
=> Check EntryPoint in Constructor

4337/src/tasks/local_verify.ts, 4337/src/utils/safe.ts, 4337/src/utils/solc.ts, 4337/test/e2e/ReferenceEntryPoint.spec.ts, 4337/test/eip4337/EIP4337Module.spec.ts, 4337/test/eip4337/EIP4337ModuleExisting.spec.ts, 4337/test/eip4337/EIP4337ModuleNew.spec.ts, 4337/test/utils/setup.ts, 4337/types/ethers.d.ts
This PR just fixes some TypeScript lints. Additional comments included inline 👇.
=> Fix TypeScript Lints

4337/README.md, 4337/contracts/test/InitCode.sol, 4337/test/docs/InitCode.spec.ts
This PR fixes the `initCode` computation code snippet in the README. I also chose to add a small test to verify the code works. Unfortunately, it is manual in that changes to the sample `initCode` computation in Solidity need to be mirrored to the README.
=> Fix initCode Computation in README

4337/hardhat.config.ts
This PR cleans up the Hardhat network configuration:
1. Renamed `xdai` to `gnosis` and updated the RPC URL
2. Got rid of old test networks and added `sepolia`
3. Got rid of energy web network, not sure what this is exactly, but I don't think it is related to 4337.
=> Clean Up Hardhat Network Configuration

4337/src/tasks/local_verify.ts
Fixed #144 
This PR modifies the `local-verify` task to ignore immutable values comparing bytecode with compiler output. This was an issue as contracts were incorrectly marked as `FAILURE` during local verification despite matching bytecode.
```
$ npx hardhat local-verify --network localhost
Verification status for AddModulesLib: SUCCESS
Verification status for HariWillibaldToken: SUCCESS
Verification status for Safe4337Mock: SUCCESS
Verification status for Safe4337Module: SUCCESS
Verification status for SafeL2: SUCCESS
Verification status for SafeMock: SUCCESS
Verification status for SafeProxyFactory: SUCCESS
Verification status for TestEntryPoint: SUCCESS
```
Note that this PR explicitly choses ignore immutable values instead of trying to verify they would match. See …
=> Ignore Immutables on Local Verification

4337/contracts/Safe4337Module.sol, 4337/contracts/test/SafeMock.sol, 4337/test/eip4337/EIP4337Module.spec.ts
Closes #157
This PR removes the redundant code to check if the entry point contract is actually supported or not.
=> Created `onlySupportedEntryPoint(...)` modifier avoiding code redundancy

4337/docker-compose.yaml, 4337/docker/bundler/Dockerfile
This PR updates the reference bundler used for E2E tests:
- It uses a newer version of the bundler that includes the exception to associated storage access for staked factories (https://github.com/eth-infinitism/bundler/pull/127).
- Uses the `--auto` flag; by default, the bundler will wait for whichever comes first of 3 second or 10 user operations before submitting a bundle, with `--auto` flag, it submits the bundle right away
Notice that the E2E test run significantly faster with this change:
```
E2E - Local Bundler
✔ should deploy a new Safe and execute a transaction (3731ms)
✔ should execute a transaction for an exsiting Safe (2880ms)
E2E - Local Bundler
✔ should deploy a new Safe and execute a transaction (912ms)
✔ should execute a transaction for an exsiting Safe (628ms)
```
=> ERC-4337 Bundler Updates

4337/contracts/Safe4337Module.sol, 4337/test/eip4337/EIP4337ModuleExisting.spec.ts, 4337/test/eip4337/EIP4337ModuleNew.spec.ts
This PR fixes a revert message propagation issue where the length of revert bytes was the **offset** of the return data in memory and not its actual length 🤦. It turns out that because of how ABI encoding works, the tests were not catching this issue since in that particular test the offset was alway larger than the actual length of the revert message. In theory, this is UB (as the offset it not guaranteed to be larger than the message, although, in practice it is not a serious issue, as it appears the compiler is allocating memory for the raw `call` result and then **copying with a loop** the ABI-decoded `returnData` memory bytes after it, so the offset of `returnData` will always be greater than its size, and the current implementation just returns too many bytes).
Adjusted tests to …
=> Fix Revert message propagation

4337/contracts/Safe4337Module.sol, 4337/contracts/test/SafeMock.sol, 4337/src/utils/execution.ts, 4337/src/utils/safe.ts, 4337/src/utils/userOp.ts, 4337/test/e2e/LocalBundler.spec.ts, 4337/test/eip4337/ReferenceEntryPoint.spec.ts, 4337/test/eip4337/Safe4337Module.spec.ts
Fixes #160 
This PR fixes the `checkSignatures` call to the Safe to include both the Safe operation hash for recovery, but also the encoded operation bytes, which is required when using an ERC-1271 signer. In order to test this, the `SafeMock` now requires that `dataHash == keccak256(data)` and I added a unit test using a nested Safe set (note that this would require a staked paymaster to work with 4337 bundlers, but the test does check that the contract signatures works as expected).
=> Send encoded Safe operation bytes to `checkSignatures` call

4337/contracts/Safe4337Module.sol, 4337/contracts/test/SafeMock.sol, 4337/src/utils/execution.ts, 4337/src/utils/userOp.ts, 4337/test/e2e/LocalBundler.spec.ts, 4337/test/eip4337/ReferenceEntryPoint.spec.ts, 4337/test/eip4337/Safe4337Mock.spec.ts, 4337/test/eip4337/Safe4337Module.spec.ts, 4337/test/utils/encoding.ts
Follow up to #143 and #156
This PR refactors signature validation to use the immutable `SUPPORTED_ENTRYPOINT` value instead of passing it into various functions. This has the benefit of freeing up a stack slot for an additional variable. This means that we can now sign `validAfter` and `validUntil` as separate fields in our `SafeOp` struct (which should provide a nicer user experience for signing and be less cryptic than using a “signatureTimestamps” field that combines both values).
The caveat is that `getOperationHash` is tied to the module’s supported `EntryPoint` value, but IMO this makes more sense that what we had before, as signatures for other `EntryPoint`s are useless to it anyway.
Additionally, in theory, we don’t need to include the `entryPoint` in the signature, since it is …
=> [4337] Separate Signature Fields for `validAfter` and `validUntil`

4337/contracts/Safe4337Module.sol, 4337/contracts/test/SafeMock.sol
In preparing for the v0.1.1 audit, I noticed we (i.e. me) forgot to follow internal function naming convention for `_getOperationData`. This PR fixes that (already fixed in the `v0.1` branch) and moves the function down closer to the other `internal` functions.
=> Internal Function Naming Convention

4337/README.md
1. Fix the dead link for the releases page (follow-up: do tags like 0.1.0 work well for a monorepo?)
2. Remove the compiler settings from the section; we have a separate section about compiler settings.
=> Update `deploy` section in the readme

4337/CHANGELOG.md, 4337/README.md
This PR adds a deployment documentation section similar to the [Safe contracts](https://github.com/safe-global/safe-contracts#deployments) and a changelog file containing the important contract changes.
Note that for the changelog, I only include the PR title and a link, as the relevant context can be found there (and didn't want to duplicate it in the CHANGELOG file).
=> Document Deployment Process and Changelog

4337/docs/v0.1.0/audit.md
This PR just updates the disclaimer in the v0.1.0 audit file to correctly render its ⚠️ icons.
It looks like VS Code renders markdown slightly differently than GH.
=> Fix Disclaimer Warning Icons

4337/contracts/test/FCL/FCL_Webauthn.sol, 4337/contracts/test/FCL/FCL_ecdsa_utils.sol, 4337/contracts/test/FCL/FCL_elliptic.sol, 4337/contracts/test/FCL/VERSION.md
This PR:
- Updates the vendored FCL code with elliptic curve math fixes by Nick and minor solidity improvement we proposed converting the public key from `uint256[2] calldata` to two separate `uint256` variables
Includes:
- https://github.com/rdubois-crypto/FreshCryptoLib/pull/56
- https://github.com/rdubois-crypto/FreshCryptoLib/pull/52
- https://github.com/rdubois-crypto/FreshCryptoLib/pull/48
=> Vendor: Update vendored FCL code

4337/.solhintignore, 4337/package-lock.json, 4337/package.json, 4337/test/utils/webauthn.ts, 4337/test/webauthn/WebAuthn.spec.ts
This PR adds a `tests/utils/webauthn.ts` module that implements a shim for the Browser WebAuthn API (sometimes conflated with Passkeys).
I verified the implementation by testing both credential creation and assertion (i.e. signing) using a reference WebAuthn/Passkey server implementation (specifically `SimpleWebAuthn` which was suggested on the [Passkeys.dev website](https://passkeys.dev/docs/tools-libraries/libraries/#typescript)).
OMG debugging signature issues is annoying :sob: :sob: :sob:
=> Implement WebAuthn Shim for Passkeys tests

4337/contracts/Safe4337Module.sol, 4337/contracts/test/SafeMock.sol, 4337/test/eip4337/Safe4337Mock.spec.ts, 4337/test/eip4337/Safe4337Module.spec.ts
=> [4337] Using Hardcoded Constants

4337/.solcover.js, 4337/contracts/test/SafeMock.sol, 4337/contracts/test/SafeSignerLaunchpad.sol, 4337/contracts/test/TestEntryPoint.sol, 4337/contracts/test/TestUniqueSigner.sol, 4337/contracts/test/WebAuthnSigner.sol, 4337/test/e2e/WebAuthnSigner.spec.ts
A huge part of the way to #173
This PR adds an E2E test using the reference 4337 EntryPoint and bundler for a Safe deployment with a WebAuthn (i.e. Passkeys) signer.
Note that this E2E test is not 100% complete. In particular, we don't get test using the Safe after the launchpad deployment is completed. I want to add that test in a follow-up when I actually add the gas profiling for the WebAuthn signer.
=> Add E2E Test with WebAuthn Signer

4337/contracts/test/SafeMock.sol
I noticed that the `fallback` function implementation was not memory safe for the SafeMock contract. This PR rectifies this.
Additionally, FCL assembly is also not tagged as memory safe (but should be AFAIU). We should probably submit a PR upstream to tag assembly as memory safe.
=> Use `memory-safe` for the SafeMock Fallback Implementation

4337/docker-compose.yaml, 4337/docker/bundler/Dockerfile, 4337/src/utils/execution.ts, 4337/test/e2e/SingletonSigners.spec.ts, 4337/test/e2e/WebAuthnSigner.spec.ts, 4337/test/eip4337/EIP4337WebAuthn.spec.ts, 4337/test/eip4337/ReferenceEntryPoint.spec.ts, 4337/test/utils/setup.ts, 4337/test/utils/webauthn.ts
Fixes #173 
This PR adds tests that execute user operations on Safes with WebAuthn signers over the reference entrypoint and prints out the gas usage. It includes both Safe deployment as well as regular user operation usage.
The results are in:
```
Safe4337Module - WebAuthn Owner
executeUserOp - new account
Used 2293926 gas for >WebAuthn signer Safe deployment<
✔ should execute user operation (357ms)
executeUserOp - existing account
Used 374142 gas for >WebAuthn signer Safe operation<
✔ should execute user operation (229ms)
```
=> Add Gas Metering Tests for WebAuthn Signers

.github/workflows/certora.yml
Fixes #169 
Changes in PR:
- Update `certora.yml` file to refer `main` instead of `master`
=> [#169] Change branch name to main in certora.yml

modules/4337/contracts/experimental/SafeSignerLaunchpad.sol, modules/4337/contracts/experimental/SignatureValidatorConstants.sol, modules/4337/contracts/experimental/WebAuthnSigner.sol
This PR:
- Adds an updated EIP-1271 validation method to the WebAuthnSigner contract for futureproofing
- I created an abstract contract with both magic values, similar to how it's done in the Safe Account contract. We cannot reuse the Safe's contract because it only includes one value (either the legacy or the new one)
- I had to adjust the return values of signature-validating functions slightly. For the generic `checkSignatures` function, I changed it to a boolean, similar to how it's done in the underlying FCL's validation function
=> Add an updated EIP-1271 function to the WebAuthn signer

.github/workflows/certora.yml, modules/4337/certora/specs/Safe4337Module.spec, modules/4337/certora/specs/TransactionExecutionMethods.spec
This PR:
- Upgrades certora cli spec file with V6 changes, mainly the change around how ghost variables are handled - now they may be HAVOC'ed between unresolved calls and we need to add the `persistent` keyword to persist them
=> Feature: Upgrade `certora-cli` version to v6

.gitignore, modules/4337/contracts/Safe4337Module.sol
Changes the NatSpec of `SUPPORTED_ENTRYPOINT` with the correct description.
Closes #214
Nit: Also added `.vscode` to `.gitignore`.
=> Fix EntryPoint Natspec

modules/4337/contracts/experimental/WebAuthn.sol, modules/4337/contracts/experimental/WebAuthnSigner.sol, modules/4337/test/e2e/WebAuthnSigner.spec.ts, modules/4337/test/erc4337/ERC4337WebAuthn.spec.ts, modules/4337/test/utils/webauthn.ts
Fixes #220 
This PR proposes a new signature encoding scheme for the Webauthn signer. This takes advantage of the [`clientDataJSON` serialization specification]() which requires a specific ordering and formatting (no additional whitespace) for the fields). Notably, this scheme:
* reduces the amount of calldata by 114 bytes per signature; this is non-trivial in the context of reducing calldata for rollups (where calldata is more expensive than computation).
* no longer requires a trusted `challengeOffset` (which has some security implications).
I plan to upstream these changes to FCL after doing a bit of investigation on potentially optimizing:
- base64 encoding of the challenge (since we use a fixed 32-byte challenge while the library allows for arbitrary `bytes`)
- byte concatenation …
=> New Signature Encoding for Webauthn Signer

examples/safe-4337-passkeys/package.json, examples/safe-4337-passkeys/src/logic/safe.ts, package-lock.json
This PR:
- Fixes broken install step by replacing references to previously renamed `@safe-global/safe-eip4337` package
=> Fix reference to inexisting package `@safe-global/safe-eip4337`

modules/4337/contracts/Safe4337Module.sol
This PR reverts the `SUPPORTED_ENTRYPOINT` NatSpec documentation fix from safe-global/safe-modules#216. This issue was reported as part of the OZ audit, and should be fixed as part of a separate process.
Just reverting here to make that process easier.
=> Revert EntryPoint Natspec Fix

.github/workflows/ci_4337_upstream_bundler.yml, modules/4337/docker-compose.yaml, modules/4337/docker/bundler/Dockerfile, modules/4337/package.json, modules/4337/test/e2e/run.sh
As vaguely explained by the OpenZeppelin team, the primary motivation for M-01 is not compatibility with unreleased versions but a more prompt awareness of the new potential changes in the ERC-4337 standard, as they deemed incompatibility with the standard as one of the leading security concerns for the protocol.
This PR presents an alternative solution for M-01 by adding a secondary e2e test job that uses an upstream version of the bundler for the test. This should test both the `Entrypoint <> Module` API compatibility (because the bundler will deploy its own Entrypoint to the locally running geth chain) as well as the storage access rules. The test also runs on schedule (1st and 15th of each month)
=> [M-01] Potential Obsolescence for `Safe4337Module`

modules/4337/contracts/AddModulesLib.sol, modules/4337/contracts/Safe4337Module.sol
This PR addresses the issue L-01 from the audit report.
Specifically, it implements the suggestion to not use floating pragmas, but specific Solidity compiler versions for the contracts.
=> [L-01] Specific Solidity Version for Contracts

modules/4337/contracts/Safe4337Module.sol
This PR addresses issue `L-02` from the audit report.
In particular it fixes two comments that were found to be inaccurate:
1. `SUPPORTED_ENTRYPOINT` NatSpec documentation
2. Comment explaining which contract was responsible for appending the `msg.sender` as per [ERC-2771](https://eips.ethereum.org/EIPS/eip-2771).
Additionally, I went through other comments in `Safe4337Module.sol` for additional errors (but did not find any).
=> [L-02] Fix Misleading Comments in Contract Code

modules/4337/.env.sample, modules/4337/README.md, modules/4337/contracts/SafeModuleSetup.sol, modules/4337/contracts/test/InitCode.sol, modules/4337/scripts/runOp.ts, modules/4337/src/deploy/libraries.ts, modules/4337/src/utils/safe.ts, modules/4337/test/docs/InitCode.spec.ts, modules/4337/test/e2e/LocalBundler.spec.ts, modules/4337/test/e2e/SingletonSigners.spec.ts, modules/4337/test/e2e/UniqueSigner.spec.ts, modules/4337/test/e2e/WebAuthnSigner.spec.ts, modules/4337/test/erc4337/ERC4337ModuleNew.spec.ts, modules/4337/test/erc4337/ERC4337WebAuthn.spec.ts, modules/4337/test/erc4337/ReferenceEntryPoint.spec.ts, modules/4337/test/gas/Gas.spec.ts, modules/4337/test/utils/setup.ts
This PR contains fixes to 3 issues from the audit report. They were combined into a single PR in order to prevent git merge conflicts once the review is complete. Each fix is in an individual commit to facilitate the review.
There were missing NatSpec documents for both the `SafeModuleSetup` (formerly `AddModulesLib`) contract and `enableModules` function. Both were added to ensure high quality documentation.
The `enableModules` function used a reverse loop to go through the modules to add. This was done in order to preserve module order and _thought_ to be slightly more gas efficient. It turns out to not be the case with the current compiler and flags. The loop was changed into a forward loop, making both the implementation more clear, but also slightly more gas efficient.
The module …
=> [L-03, N-01, N-02] Fixes to `SafeSetupModule` (formerly `AddModulesLib`)

modules/4337/contracts/Safe4337Module.sol
Fixes audit issue N-04.
This PR adds the custom `security-contact` tag to the `Safe4337Module` contract NatSpec documentation.
Note that the audit issue additionally mentioned that the `AddModulesLib` contract also needed a security contract, but this was added as part of the NatSpec documentation when resolving L-03 in #241.
=> [N-04] Add Security Contact to NatSpec

modules/4337/contracts/Safe4337Module.sol
This PR makes the use of named returns consistent throughout the module contract. In particular, `domainSeparator` is the only function to not use named returns in the `Safe4337Module` contract.
=> [N-06] Consistent Named Returns

modules/4337/test/e2e/run.sh
This PR modifies the E2E `run.sh` script to allow configuration of the Docker CLI to use. Why? I use `podman` instead of `docker`. Another potential use case would be to use a specific `docker` client instead of the one configured in `$PATH`.
I can now successfully run:
```
DOCKER=podman npm run test:e2e
```
Note that not specifying any configuration in the environment will cause the script to default ot the `docker` command. On my system without `docker` installed:
```
$ npm run test:e2e
> @safe-global/safe-erc4337@0.2.0 test:e2e
> ./test/e2e/run.sh
./test/e2e/run.sh: line 5: docker: command not found
```
=> Allow Specifying Docker CLI For E2E

modules/4337/contracts/experimental/SafeSignerLaunchpad.sol, modules/4337/contracts/experimental/SignatureValidator.sol, modules/4337/contracts/experimental/WebAuthnSigner.sol, modules/4337/contracts/test/TestUniqueSigner.sol
This PR slightly refactors the WebAuthn signature validation logic in preparation for sharing code when implementing #228.
Essentially, it creates a `SignatureValidator` abstract base class for sharing that supports both legacy and current EIP-1271 functions. As a consequence of the refactoring, `ISafeSingletonSigner` now uses `bytes32` messages for signature validation instead of `bytes memory`, in order to be more of an analogy to the current EIP-1271 standard (instead of the legacy one).
=> Refactor WebAuthn Signature Validation Logic

modules/4337/contracts/experimental/SignatureValidator.sol, modules/4337/contracts/experimental/WebAuthnSigner.sol, modules/4337/contracts/experimental/verifiers/P256Verifier.sol, modules/4337/contracts/experimental/verifiers/P256Wrapper.sol, modules/4337/contracts/experimental/verifiers/WebAuthnVerifier.sol, modules/4337/test/e2e/run.sh
This PR addresses some lint warnings I found when working on #254. Additionally, I also:
- made the wording around "signed message" more consistent throughout the code
- fixed the E2E Bash script to report errors when tests fail
=> Fix Lint Warnings And Other Small Cleanups

modules/4337/contracts/experimental/WebAuthnSingletonSigner.sol, modules/4337/test/e2e/WebAuthnSingletonSigner.spec.ts
Fixes #228 
This PR implements a WebAuthn Singleton Signer and verifies it works with the 4337 reference bundler.
In particular, this uses the same strategy introduced by #159, but specific to Passkey + WebAuthn. Note that, unlike the Safe launchpad + WebAuthn signer factory strategy, this requires a **staked factory**.
=> Implement Webauthn Singleton Signer PoC

modules/4337/CHANGELOG.md, modules/4337/README.md
This PR:
- Partially solves https://github.com/safe-global/safe-modules/issues/231 (partially because the issue says 0.7.0 which isn't released yet)
- I decided to include the supported entrypoint version and address in the changelog because the official deployment is tied to a certain entrypoint which, in my opinion, should be documented.
=> Document supported entrypoint versions

modules/4337/test/e2e/SingletonSigners.spec.ts
The singleton signer E2E test would [sometimes fail](https://github.com/safe-global/safe-modules/actions/runs/7841917436/job/21399201219). Flaky tests are evil...
It turns out that this is for a fairly simple reason. The test singleton signer key is expected to be exactly 32 bytes long:
https://github.com/safe-global/safe-modules/blob/ed765e2e882f3c12d264a45f8152cdcdebb1a216/modules/4337/contracts/test/TestSingletonSigner.sol#L21
Looking at the error output from the above test, we see that one of the encoded test singleton signer keys was encoded to only be 31 bytes long:
```
000000000000000000000000000000000000000000000000000000000000001f
203a672226f49702ad0b8e30a27ab23729f9d164492e1209008ab1f7763df9
```
This is because we are encoding the signature with `ethers.toBeHex`, which will …
=> Fix Singleton Signer E2E Test Flakiness

modules/4337/contracts/Safe4337Module.sol, modules/4337/contracts/test/SafeMock.sol, modules/4337/package.json, modules/4337/scripts/runOp.ts, modules/4337/src/utils/safe.ts, modules/4337/src/utils/userOp.ts, modules/4337/test/e2e/UniqueSigner.spec.ts, modules/4337/test/e2e/WebAuthnSigner.spec.ts, modules/4337/test/e2e/WebAuthnSingletonSigner.spec.ts, modules/4337/test/erc4337/ERC4337WebAuthn.spec.ts, modules/4337/test/erc4337/Safe4337Module.spec.ts, package-lock.json
Fixes #250 
This PR changes the `SafeOperation` type to include ALL gas parameters for signing, instead of packing them. This ensures the maximum amount of data is available to the user when signing user operations, instead of trusting gas parameters from a Dapp.
Note a subtle change in the order of the "fee per gas" fields, this was done to match the order in the `PackedUserOperation` struct, as well as the order in EIP-1559 transactions. I figured, since we are changing the signing format anyway (notice the different integer types), this wouldn't be a big deal.
Additionally, we have a new test that verifies that `safeOp` hashes are computed off-chain in the same way they are computed on-chain. This is to catch issues with field orders being slightly different in the `EncodedSafeOp` …
=> Sign All Gas Limit and Price Parameters

modules/4337/CHANGELOG.md
This PR:
- Implements https://github.com/safe-global/safe-modules/issues/230 and sets the foundation for the version 0.3.0 changelog
Questions:
- Should we use the new 0.8.24 compiler?
=> Update changelog for version 0.3.0 of the module contract

examples/safe-4337-passkeys/package.json, modules/4337/CHANGELOG.md, modules/4337/contracts/Safe4337Module.sol, modules/4337/contracts/experimental/SafeSignerLaunchpad.sol, modules/4337/contracts/test/SafeMock.sol, modules/4337/contracts/test/TestStakedFactory.sol, modules/4337/package.json, modules/4337/src/deploy/entrypoint.ts, package-lock.json
With the `EntryPoint` v0.7 release right around the corner, this PR updates the branch to use the contract version that was deployed.
We manage to deploy the `EntryPoint` to the exact same address, so are definitely using the correct code :)
```bash
$ npx hardhat deploy --network hardhat | rg '"EntryPoint"'
deploying "EntryPoint" (tx: 0x1ca5c698c8f3416559c59a95356a344285fa17e674072ed9d63b0f79ba224963)...: deployed at 0x0000000071727De22E5E9d8BAf0edAc6f37da032 with 3650209 gas
```
=> Update to `EntryPoint` Release

modules/4337/contracts/test/SafeMock.sol, modules/4337/src/utils/execution.ts, modules/4337/src/utils/safe.ts, modules/4337/test/e2e/4337NestedSafe.spec.ts, modules/4337/test/e2e/SingletonSigners.spec.ts, modules/4337/test/e2e/WebAuthnSingletonSigner.spec.ts, modules/4337/test/erc4337/ERC4337WebAuthn.spec.ts, modules/4337/test/erc4337/ReferenceEntryPoint.spec.ts, modules/4337/test/utils/e2e.ts
This PR adds an E2E test case for nested Safe transaction execution in the 4337 Context. The test uses the following ownership structure:
I implemented helper classes representing the Safe ownership tree with two node types: Safe and EOA. The tests also required functions to find an execution path and build the user operation from the execution path. The alternative would've been to do everything imperatively, but using those functions, we could theoretically represent arbitrary ownership structure, find an execution path (currently, the function doesn't find the most optimal one) and generate a user operation.
The current algorithm works as follows (thanks to @nlordell for the help):
1. **Finding an execution path:** It does a DFS on the tree until it finds the first Executor node. We …
=> Add an E2E test for nested Safes in 4337 context

examples/4337-gas-metering/.prettierignore, examples/4337-gas-metering/tsconfig.json
This PR removed the formatting issue in the `4337-gas-metering` CI.
CI failure for `safe-modules-examples` remains, and will be solved later with #270
=> Formatting issue for 4337 gas metering in CI

modules/4337/contracts/Safe4337Module.sol
Trivial fix to a comment in the `Safe4337Module`.
=> Fix Safe4337Module Comment

examples/4337-gas-metering/alchemy/alchemy.ts, examples/4337-gas-metering/gelato/gelato.ts, examples/4337-gas-metering/pimlico/pimlico.ts, examples/4337-gas-metering/utils/address.ts
This PR just improves the `type` definition of `SAFE_ADDRESS_MAP` to remove some of the linting errors.
P.S. `userOps` linting errors will be solved with either #294 or #316.
=> Improving the type definition of `SAFE_ADDRESS_MAP`

modules/passkey/contracts/interfaces/IP256Verifier.sol, modules/passkey/contracts/libraries/P256.sol, modules/passkey/contracts/verifiers/FCLP256Verifier.sol, modules/passkey/test/verifiers/FCLP256Verifier.spec.ts
Fixes #309 
This PR fixes an issue where the FCL P-256 verifier behaviour was not following the precompile. In particular, I used the Polygon team implementation:
https://github.com/maticnetwork/bor/blob/43958943edfdfb53f8a7cbe469693b9315fad96b/core/vm/contracts.go#L1209-L1231
To validated expectations, I ran the following script against a Polygon Mumbai execution node to inspect the precompile return values:
<details><summary><code>test-rip-7212.sh</code></summary>
```sh
echo "just right"
curl -s -X POST "$NODE_URL" -H 'Content-Type: application/json' --data '@-' <<JSON | jq -r .result
{
"jsonrpc": "2.0",
"id": 42,
"method": "eth_call",
"params": [
{
"to": "0x0000000000000000000000000000000000000100",
"data": "0xbb5a52f42f9c9261ed4361f59422a1e30036e7c32b270c8807a419feca6050232ba3a8be6b94d …
```
=> Correct EIP-7212 Behaviour

modules/passkey/test/utils/p256.ts
This PR fixes a small bug in the P-256 account implementation used for tests. It provides an interface that exposes both a high and low S value for a P-256 ECDSA signature, but computes it in a way that the ordering isn't stable (and leads to failed assertions some of the times).
Likely a copy-pasta issue from copying signing code from the `webauthn.ts` module (which does not care abot signature malleability).
=> Fix P-256 Test Account Implementation

modules/passkey/test/userStories/rotatePasskeyOwner.ts
Fixes #279 
Changes in PR:
- Add a test case to showcase that a Passkey signer for a Safe can be replaced with new signer. The signer is replaced by an EOA which is also a Safe owner.
Tasks:
- Add test case
- Add comments
=> User story: Swap passkey owner

modules/passkey/package.json, modules/passkey/test/GasBenchmarking.spec.ts
In order to explore some small code improvements, this PR adds a new NPM script to the passkey module to make it easier to invoke only the benchmark tests.
=> Add NPM Benchmarking Script

modules/passkey/contracts/libraries/WebAuthn.sol, modules/passkey/contracts/test/TestWebAuthnLib.sol
When looking for low-hanging fruit for gas optimisations, I noticed that Solidity was generating copy loops when calling the SHA-256 precompile, even if the input was already in memory!
This PR provides a work around where we re-implement the SHA-256 precompile manually in a way that it never copies the input before doing the `staticcall`. This gives us some substantial gas savings, both in terms of deployment costs and runtime costs:
<details><summary>Before:</summary>
```
Gas Benchmarking [@bench]
WebAuthnSigner
⛽ deployment: 515421
✔ Benchmark signer deployment cost (765ms)
⛽ verification (Dummy): 12106
✔ Benchmark signer verification cost with Dummy verifier
```
</details>
<details><summary>After:</summary>
```
Gas Benchmarking [@bench]
WebAuthnSigner
⛽ deployment: 471398
✔ Benchmark …
```
=> Manually Implement SHA-256 Precompile Call

modules/passkey/test/userStories/executeUserOpFromPasskeySigner.ts
Fixes #277 
Changes in PR:
- Add a test case to showcase that a Passkey signer can sign a `userOp` and execute transactions through a Safe. 
Tasks:
- Add test case
- Add comments
=> User story: Execute userOp with Passkey signer

modules/passkey/contracts/libraries/WebAuthn.sol, modules/passkey/contracts/test/TestWebAuthnLib.sol, modules/passkey/test/libraries/WebAuthn.spec.ts
Closes #292 
This PR generalizes the `WebAuthn` library to work better with future public key algorithms that we may want to implement. Notably, the hashing algorithm used for signing depends on the public key algorithm of the credential, and is not always SHA-256. In contrast, the client data JSON is **always** hashed with SHA-256. As such, we refactored the function to return the actual signing message before hashing, so it can be more easily composed in the eventuality that we start to support other algorithms.
We also refactor encoding to be done in assembly for some small gas wins, because Solidity is double copying the authenticator data.
<details><summary>Before:</summary>
```
Gas Benchmarking [@bench]
WebAuthnSigner
⛽ deployment: 471398
✔ Benchmark signer deployment cost (761ms)
⛽ …
```
=> Generalize Signing Message Encoding

examples/4337-passkeys/README.md, examples/4337-passkeys/src/logic/safe.ts, modules/passkey/contracts/SafeWebAuthnSigner.sol, modules/passkey/contracts/SafeWebAuthnSignerFactory.sol, modules/passkey/contracts/libraries/P256.sol, modules/passkey/src/deploy/webauthn.ts, modules/passkey/test/4337/WebAuthn.spec.ts, modules/passkey/test/4337/WebAuthnSigner.spec.ts, modules/passkey/test/GasBenchmarking.spec.ts, modules/passkey/test/userstories/CreateSafeWithPasskeySignerAsOwner.spec.ts, modules/passkey/test/userstories/ExecuteUserOpFromPasskeySigner.spec.ts, modules/passkey/test/userstories/OffchainPasskeyVerification.spec.ts, modules/passkey/test/userstories/RotatePasskeyOwner.spec.ts
This PR keeps up with the Safe's proud naming tradition of having all contract names be prefixed with Safe-.
=> Rename WebAuthn Contracts

modules/passkey/contracts/SafeWebAuthnSigner.sol, modules/passkey/test/SafeWebAuthnSigner.spec.ts, modules/passkey/test/utils/webauthn.ts
This PR adds some missing NatSpec documentation to the `SafeWebAuthnSigner` contract (notably the `immutable`s) and implements missing coverage for the contract. In the unit and E2E tests, we only ever call the `isValidSignature(bytes,bytes)` function, and never the `isValidSignature(bytes32,bytes)`.
Related to #365
=> NatSpec and Unit Test Coverage for `SafeWebAuthnSigner`

modules/passkey/test/GasBenchmarking.spec.ts, modules/passkey/test/SafeWebAuthnSigner.spec.ts, modules/passkey/test/SafeWebAuthnSignerFactory.spec.ts, modules/passkey/test/userstories/OffchainPasskeyVerification.spec.ts, modules/passkey/test/utils/erc1271.ts
Addresses https://github.com/safe-global/safe-modules/pull/371#pullrequestreview-1988230595 (cc @remedcu)
This PR addresses a comment to use constants for ERC-1271 magic values to make the tests easier to read.
=> Use ERC-1271 Constants In Tests

modules/passkey/contracts/4337/SafeECDSASignerLaunchpad.sol
Related to #308
This PR adds NatSpec documentation to the `SafeSignerLaunchpad` contract for all methods. This is done in preparation for an auditing these contracts and as a precursor to getting 100% test coverage.
In writing this PR, I found some issues with the current launchpad implementation that need to be addressed pre-audit:
- We allow accounts that haven't been properly initialized, which can be a security risk. We should do checks similar to the Safe `setup` method to prevent double initialization and the validation should revert if the account is not initialized.
- We are using revert messages instead of errors.
Additionally, I would like to suggest that we change the implementation to use a **single** setup instead of doing a pre- and post- setup delegatecall. This would …
=> Add NatSpec Documentation To The Safe Launchpad

examples/4337-passkeys/README.md, examples/4337-passkeys/src/logic/safe.ts, modules/passkey/contracts/4337/SafeSignerLaunchpad.sol, modules/passkey/contracts/SafeWebAuthnSigner.sol, modules/passkey/contracts/SafeWebAuthnSignerFactory.sol, modules/passkey/contracts/interfaces/ISafeSignerFactory.sol, modules/passkey/contracts/libraries/P256.sol, modules/passkey/contracts/libraries/WebAuthn.sol, modules/passkey/contracts/test/TestP256Lib.sol, modules/passkey/contracts/test/TestWebAuthnLib.sol, modules/passkey/contracts/test/TestWebAuthnSingletonSigner.sol, modules/passkey/src/deploy/launchpad.ts, modules/passkey/test/4337/WebAuthn.spec.ts, modules/passkey/test/4337/WebAuthnSigner.spec.ts, modules/passkey/test/4337/WebAuthnSingletonSigner.spec.ts, modules/passkey/test/GasBenchmarking.spec.ts, modules/passkey/test/SafeWebAuthnSigner.spec.ts, modules/passkey/test/SafeWebAuthnSignerFactory.spec.ts, modules/passkey/test/libraries/P256.spec.ts
This PR changes the internal workings of the signers to accept a uint192 instead of an address as the `verifier` (well, now `verifiers`) parameter. This allows a signer to encode BOTH a precompile address as well as a Solidity implementation fallback for the P-256 curve.
Additionally, this required changing the interface of the `ICustomECDSASignerFactory`. It is now very much tied to the P-256 implementation that we have, and as such I renamed things to just `ISafeSignerFactory` and `SafeSignerLaunchpad`, since it is not a general ECDSA solution, but one that is particular to the P-256 implementation that we have and in particular supporting P-256 precompile with Solidity fallback.
The PR changes **a lot** of files, but this is mostly small modifications to tests. Unfortunately, I don't …
=> Support Precompile With Fallback For Signers

modules/passkey/test/4337/WebAuthnSingletonSigner.spec.ts, modules/passkey/test/SafeWebAuthnSignerFactory.spec.ts, modules/passkey/test/libraries/P256.spec.ts, modules/passkey/test/libraries/WebAuthn.spec.ts, modules/passkey/test/userstories/RotatePasskeyOwner.spec.ts, modules/passkey/test/utils/hardhat.ts, modules/passkey/tsconfig.json
I needed to import types for the example application type from the passkey package and I discovered that types were not included in the production build
This PR:
- Adds `typechain-types` folder to the build in typescript config
- Fixes the type errors that arose
Notes:
- The PR doesn't include other type improvements --> for example, there are many occurrences of `new ethers.Contract(abi, address, provider)` which would be of a high-level type `Contract`, but we have a type for the contract and could cast it to a more narrow type
- After the PR gets approved, I will create pump the package version number and push a beta release
=> Passkey package: Add typechain types to the typescript build, fix types

modules/passkey/package.json
This PR bumps the version of the passkey package to 0.2.0-alpha.0 
Changes:
- Add `typechain-types` to the package
Following the release, we will also deprecate version 0.1.0
=> Passkey: release `0.2.0-alpha.0`

modules/passkey/package.json, modules/passkey/tsconfig.json
This PR fixes the bug where the build didn't include typescript declaration files (*.d.ts) by setting the corresponding option to `true` in the typescript config. It also bumps the version number to `0.2.0-alpha.1`
=> Passkey: Generate declaration files, bump version to alpha.1

modules/passkey/README.md, modules/passkey/hardhat.config.ts, modules/passkey/package.json, modules/passkey/src/tasks/deployContracts.ts, modules/passkey/src/tasks/localVerify.ts
I needed to deploy the passkeys contracts and found out that there's no deploy command/task
This PR:
- Adds a `deploy-all` task to the passkey package, similarly to how its used in other packages (4337 and safe-smart-account)
The command works (doesn't include output from failed attempts where I had to increase gas price):
```
npm run deploy-all sepolia -w modules/passkey
> @safe-global/safe-passkey@0.2.0-alpha.1 deploy-all
> hardhat deploy-contracts --network sepolia
Nothing to compile
No need to generate any newer typings.
reusing "SafeSignerLaunchpad" at 0xf9E93EfBF37B588f9c79d509c48b87A26c3DfEB9
reusing "DaimoP256Verifier" at 0xc2b78104907F722DABAc4C69f826a522B2754De4
reusing "FCLP256Verifier" at 0xcA89CBa4813D5B40AeC6E57A30d0Eeb500d6531b
reusing "SafeWebAuthnSignerFactory" at …
```
=> Feature: Add deploy-all task to passkeys

modules/4337/.solhint.json, modules/passkey/.solhint.json, modules/passkey/contracts/libraries/WebAuthn.sol, modules/passkey/contracts/test/TestWebAuthnLib.sol, modules/passkey/test/libraries/WebAuthn.spec.ts
This PR adds logic to verify the WebAuthn signature encoding length. This is done so that encodings have a strict upper bound (determined by the 'standard' ABI encoding of the `WebAuthn.Signature` struct) on the length of the signatures.
This prevents a potential griefing attack where the signature that is sent to an ERC-4337 bundler could be arbitrarily padded with additional `0`s (which would have trivial increases to the `calldatasize` with onchain LZMA calldata decompression that already exists) while causing accounts to pay significantly more in gas costs for signature verification (bounded by the `verificationGasLimit`).
=> Verify WebAuthn Signature Encoding

modules/passkey/contracts/SafeWebAuthnSignerFactory.sol, modules/passkey/test/libraries/WebAuthn.spec.ts
This PR gets us to 100% branch coverage on all contracts, the two that didn't have 100% coverage were:
- `SafeWebAuthnSignerFactory`: There was a `require` for something that should never be false, so it was changed to an `assert`
- `WebAuthn`: There was an else path that wasn't covered, so an additional unit test for that branch was added
=> 100% Branch Coverage On Contracts

modules/passkey/contracts/SafeWebAuthnSignerFactory.sol, modules/passkey/contracts/SafeWebAuthnSignerProxy.sol, modules/passkey/contracts/SafeWebAuthnSignerSingleton.sol, modules/passkey/contracts/interfaces/ISafe.sol
This PR uses assembly to encode the calldata for calling the WebAuthn signer singleton instead of using native Solidity. This has notable improvements to the deployment gas costs:
**Before**:
```
SafeWebAuthnSignerProxy
⛽ deployment: 107899
✔ Benchmark signer deployment cost (867ms)
```
**After**:
```
SafeWebAuthnSignerProxy
⛽ deployment: 92481
✔ Benchmark signer deployment cost (849ms)
```
This is a result of reduced codesize and not significantly more performant code.
---
I also cleaned up some comments in this PR.
=> Optimize WebAuthn Signer Proxy Implementation

modules/passkey/contracts/test/TestDependencies.sol, modules/passkey/test/4337/Safe4337Module.spec.ts, modules/passkey/test/4337/SafeWebAuthnSharedSigner.spec.ts
Fixes #407 
This PR adds unit tests for 100% code coverage for the Safe shared WebAuthn signer contract.
=> 100% Test Coverage for Safe WebAuthn Shared Signer

modules/passkey/contracts/4337/SafeSignerLaunchpad.sol, modules/passkey/contracts/test/TestDependencies.sol, modules/passkey/test/4337/SafeSignerLaunchpad.spec.ts
This PR adds 100% code coverage as unit test for the Safe signer launchpad contract.
```
----------------------------------|----------|----------|----------|----------|----------------|
File                              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------------|----------|----------|----------|----------|----------------|
contracts/4337/                  |      100 |      100 |      100 |      100 |                |
SafeSignerLaunchpad.sol         |      100 |      100 |      100 |      100 |                |
----------------------------------|----------|----------|----------|----------|----------------|
```
This was introduced as one large PR as I don't see much value in splitting this into individual PRs for review (all changes are …
=> 100% Code Coverage on Signer Launchpad

modules/passkey/test/userstories/DeterministicPasskeySignerAddress.spec.ts
This PR adds an additional user story demonstrating how the passkey signer is deployed to a deterministic address that can be computed off-chain.
=> Add User Story For Determinstic Deployment

modules/passkey/test/4337/SafeWebAuthnSigner.spec.ts, modules/passkey/test/4337/experimental/Safe4337Module.spec.ts, modules/passkey/test/4337/local-bundler/SafeWebAuthnSigner.spec.ts, modules/passkey/test/4337/local-bundler/experimental/SafeSignerLaunchpad.spec.ts, modules/passkey/test/4337/local-bundler/experimental/SafeWebAuthnSharedSigner.spec.ts
Follow up to #415
Now that we officially tagged the launchpad as "experimental", the module was missing unit and E2E tests demonstrating the "officially" supported way to use passkeys over ERC-4337. This PR adds both a unit test that a user operation with a passkey owner can be executed over the ERC-4337 reference entrypoint, as well as a local bundler test to ensure that no bundler rules are violated by the passkey signers.
=> Add Additional ERC-4337 Related Passkey Tests

modules/passkey/src/deploy/launchpad.ts, modules/passkey/src/deploy/webauthn.ts, modules/passkey/test/4337/local-bundler/SafeWebAuthnSigner.spec.ts, modules/passkey/test/4337/local-bundler/experimental/SafeWebAuthnSharedSigner.spec.ts
This PR demonstrates that the launchpad is, in fact, kind of useless.
Specifically, a new local bundler end-to-end test is added where the shared signer is used to create a Safe that ends up with the same configuration as with the signer launchpad. It uses the shared signer as the initial owner which is used for signing **only** the first user operation. During execution of the first user operation, the Safe's owner is swapped for a freshly deployed `SafeWebAuthnSignerProxy` instead of the shared signer. This means that we end up with a Safe with a "regular" passkey owner without any of the downsides (complicated launchpad code, rigid ownership structure, only one passkey owner allowed, etc.).
If this PR is approved, I will **remove** the `SafeSignerLaunchpad` in follow up PRs as well as …
=> Local Bundler Test with New Shared Signer Flow

modules/passkey/contracts/4337/experimental/SafeWebAuthnSharedSigner.sol, modules/passkey/test/4337/experimental/SafeWebAuthnSharedSigner.spec.ts
I noticed a small documentation issue in the Safe shared WebAuthn signer implementation. This PR fixes it.
In addition, I added an assertion to ensure that we don't write any storage to a slot for which we know a pre-image.
=> Fix Documentation in WebAuthn Shared Signer

modules/passkey/docker-compose.yaml, packages/4337-local-bundler/docker-compose.yaml
This PR removes the Docker compose version from the `docker-compose.yaml` files since they are obsoleted (thanks @remedcu for pointing this out).
I also added a `name` field, so that the name remains constant even if we move the docker compose files around (defaults to the parent directory name).
=> Remove Docker Compose Version

modules/4337/package.json, modules/4337/scripts/runOp.ts, modules/4337/src/utils/safe.ts
I was running the 4337 `runOp.ts` script this morning and noticed it was subtly broken. This PR fixes it.
I also refactored the scripts a bit - specifically we no longer `--fix` on `lint:ts`. This was because it would cause CI to silently pass in cases where the linter could autofix the code (when we want it to fail instead).
=> Fix `runOp` Script

modules/passkey/contracts/4337/experimental/SafeWebAuthnSharedSigner.sol, modules/passkey/contracts/test/TestDependencies.sol, modules/passkey/contracts/test/TestSharedWebAuthnSignerAccessor.sol, modules/passkey/test/4337/experimental/SafeWebAuthnSharedSigner.spec.ts
This PR changes the behaviour of the shared signer to store its configuration as if it were behind a mapping where the key is the shared signer address. This allows multiple shared signer instances to be configured for a single account (in case you ever need to deploy a 2/2 Safe owned by passkeys with 4337).
I created an "accessor" contract to prove that the storage location is indeed the equivalent to a `mapping(address self => Signer)`.
=> Shared Signer Mapping

modules/4337/contracts/test/TestSafeSignerLaunchpad.sol
The test/example Safe signer launchpad pattern in the ERC-4337 module directory did not contain an important security check preventing double initialization which could lead to an account being taken over.
In order to better document the security requirements for such a contract, we added the double initialization check to the pre-validation setup.
Huge kudos to Ackee Blockchain for bringing this to our attention :muscle:.
=> Check for Double Initialization

modules/passkey/README.md, modules/passkey/src/tasks/deployContracts.ts
The `deployContracts` task currently only verifies contracts on Etherscan on deployment, instead of Etherscan + Sourcify. This PR fixes the script to verify contract code on both.
=> Verify Contracts on Sourcify With Deployment

examples/4337-passkeys/package.json, examples/4337-passkeys/src/config.ts, pnpm-lock.yaml
Now that we have released the passkey package, the 4337 example can be updated to use the released packages instead of the development code.
I also change the configuration to make use of the `*-deployments` packages to make sure the example works on the "real" addresses.
I manually ran the example application and was successful with creating and executing user operations:
- [Safe creation userOp](https://sepolia.etherscan.io/tx/0xdcab84d43b4bbd954c13fd991615c2490b0c6e59a058e46764d2875e6dbf4e4f)
- [Transfer userOp](https://sepolia.etherscan.io/tx/0x15210fb522c94907bc38bb99cc9b1020a20e32e19c517f8fed04f607c9c1d666)
=> Update Passkey Example for Release

modules/4337/package.json, modules/passkey/package.json, pnpm-lock.yaml
This PR:
- Implements https://github.com/safe-global/safe-modules/issues/426 by releasing the code we have now under a new tag
- There were no contract changes, so the expected addresses are the same. I confirmed it by trying to deploy to a network where the contracts are already deployed:
```
> hardhat deploy-contracts --network "mainnet"
Nothing to compile
No need to generate any newer typings.
reusing "SafeModuleSetup" at 0x2dd68b007B46fBe91B9A7c3EDa5A7a1063cB5b47
reusing "Safe4337Module" at 0x75cf11467937ce3F2f357CE24ffc3DBF8fD5c226
```
=> Feature: 4337 module `v0.3.0-1`

modules/passkey/contracts/interfaces/ISafeSignerFactory.sol
As discussed internally with the team, we decided to index the `signer` field of the `Created` event from the passkey factory contract. This came as a follow up to event discussions from an issue raised from the Hats audit competition: https://github.com/hats-finance/Safe-0x2909fdefd24a1ced675cb1444918fa766d76bdac/issues/3
Note that this only slightly increases the deployment costs:
```
=== BEFORE ===
Gas Benchmarking [@bench]
SafeWebAuthnSignerProxy
⛽ deployment: 94366
✔ Benchmark signer deployment cost (476ms)
=== AFTER  ===
Gas Benchmarking [@bench]
SafeWebAuthnSignerProxy
⛽ deployment: 94476
✔ Benchmark signer deployment cost (476ms)
```
For reference, this is a 0.1% increase to the deployment gas costs.
=> Index Signer In Created Event

modules/passkey/contracts/4337/SafeWebAuthnSharedSigner.sol, modules/passkey/contracts/SafeWebAuthnSignerFactory.sol, modules/passkey/contracts/verifiers/FCLP256Verifier.sol, modules/passkey/hardhat.config.ts
I noticed that the IR optimizer is better for all contracts **except** the FCL library. This PR optimizes the compiler configuration to take advantage of the IR optimizer, while adding an exception for the FCL P-256 verifier contract so that it does not suffer any regressions.
```
=== BEFORE ===
Gas Benchmarking [@bench]
SafeWebAuthnSignerProxy
⛽ deployment: 94366
✔ Benchmark signer deployment cost (476ms)
⛽ verification (FreshCryptoLib): 216907
✔ Benchmark signer verification cost with FreshCryptoLib verifier (116ms)
⛽ verification (Daimo): 346809
✔ Benchmark signer verification cost with Daimo verifier (103ms)
⛽ verification (Dummy): 14309
✔ Benchmark signer verification cost with Dummy verifier (100ms)
⛽ verification (Precompile): 15098
✔ Benchmark signer verification cost with …
```
=> Optimize Compiler Settings

modules/4337/contracts/test/SafeMock.sol
In https://github.com/safe-global/safe-modules/pull/446, I inlined the signature check function because we didn't want it to revert in unsuccessful cases. I inlined it because the `try/catch` statement didn't work for internal function calls. Little did I know that I could do `this.f()` and that would use the `CALL` opcode instead of `JUMP`, making the `try/catch` statement possible
More info: https://www.perplexity.ai/search/if-i-call-1VYIfl5eQEWvJ302U7wVOA#0
=> `Safe4337Mock`: Remove signature check function inlining and call the function via call instead

modules/passkey/contracts/4337/SafeWebAuthnSharedSigner.sol, modules/passkey/test/4337/SafeWebAuthnSharedSigner.spec.ts
Fixes https://github.com/hats-finance/Safe-0x2909fdefd24a1ced675cb1444918fa766d76bdac/issues/3
This PR adds an event that is emitted on shared signer configuration. Note that the event is emitted in the context of the configured Safe account. In order to prevent event `topic0` collisions, we chose an explicitly verbose name.
With respect to indexing, we explicitly chose **not** to index any of the fields so that it matches the `Created` event:
https://github.com/safe-global/safe-modules/blob/bb5e1f7360633d5ecfb175c5d8667b2a3a1b746d/modules/passkey/contracts/interfaces/ISafeSignerFactory.sol#L13-L20
To re-iterate on the reasons we chose to not index some of the fields (same reasoning applies to `Created` event above):
- `x` and `y`: These are single-use public key coordinates attached to a …
=> Emit Event on Shared Signer Configuration

modules/passkey/contracts/4337/SafeWebAuthnSharedSigner.sol, modules/passkey/test/4337/SafeWebAuthnSharedSigner.spec.ts, modules/passkey/test/libraries/WebAuthn.spec.ts, modules/passkey/test/userstories/SafeAddressForPasskey.spec.ts
This PR partially addresses the comment https://github.com/safe-global/safe-modules/pull/456#discussion_r1666935429 (cc @mmv08).
In doing some exploration around event indexing, I found that we don't really have a good developer story for it. There are two separate passkey flows, so I will address them separately.
The flow specific to using the `SafeWebAuthnSignerFactory` contract to deploy a credential-specific WebAuthn credential owner requires a service for indexing Safe owners in order to properly search Safes that are owned by a specific credential. While the WebAuthn credential signer address can be deterministically computed (see `signerFactory.getSigner(...)` function), it does not allow for us to search for all Safes that use this signer. This is because there are multiple events …
=> Add User Story for Computing Safe Address

modules/4337/certora/conf/Safe4337Module.conf, modules/4337/certora/conf/SignatureLengthCheck.conf, modules/4337/certora/conf/TransactionExecutionMethods.conf, modules/4337/certora/conf/ValidationDataLastBitOne.conf, modules/4337/package.json, modules/passkey/package.json, pnpm-lock.yaml
Fixes #369
This PR bumps the version of `@simplewebauthn/server` to include a fix to which was causing flacky tests for our WebAuthn shim. It turns out that the library was not correctly dealing with leading zeros in the signature `r` or `s` values, which would cause the test to periodically fail (since the signature was random in each run - as both the private key and the challenge were randomly generated, meaning that we would occasionally have an `r` or `s` value with a leading `0` byte).
=> Fix Flaky WebAuthn Shim Test

modules/4337/CHANGELOG.md, modules/4337/certora/conf/Safe4337Module.conf, modules/4337/certora/conf/SignatureLengthCheck.conf, modules/4337/certora/conf/TransactionExecutionMethods.conf, modules/4337/certora/conf/ValidationDataLastBitOne.conf, modules/4337/hardhat.config.ts, modules/allowances/hardhat.config.ts, modules/allowances/package.json, modules/passkey/CHANGELOG.md, modules/passkey/hardhat.config.ts, modules/recovery/CHANGELOG.md, modules/recovery/hardhat.config.ts, package.json, pnpm-lock.yaml
This PR adds the use of `safe-singleton-factory` for deploying the `modules`.
Note:
- `allowances` already used the `safe-singleton-factory` for deployment.
- `passkey` version was not updated, as it was not deployed to any network AFAIK.
- Lock file was updated due to the addition of `safe-singleton-factory` in the root level. (Should we just install it individually for all 4 modules?)
**Open Question:** Should we update the version of the earlier deployed contracts or just overwrite it in CHANGELOG? Personally think that CHANGELOG should contain the change.
**Follow-Up Question:** If we are updating the version, then should we make a new release of the npm package?
=> Using `safe-singleton-factory` for module deployment

modules/passkey/contracts/4337/README.md
Previously, we had a note in the passkey 4337 contracts README that the shared signer contract was not audited. This is no longer true, so the note can be removed.
=> Remove Not Audited Note

modules/passkey/docker/geth/Dockerfile, modules/passkey/docker/geth/geth.patch
The docker build for the Optimism version of Geth with 7212 support was failing in CI. It turns out that this is related to a recent release of Go 1.23 which is causing Ethereum Geth and forks (such as the Optimism fork we use) to not build.
The fix it to pin to an older version of Golang (1.22 being the latest version that works). I also, in experimenting, updated the version of Optimism Geth we use to see if it would help - which it didn't, but decided to leave the change in anyhow (it is just a version bump to the source that we use to build and a small change to the patch file to account for the changed code).
=> Fix EIP-7212 Dev Node Docker Build

modules/passkey/CHANGELOG.md, modules/passkey/src/deploy/verifiers.ts, packages/4337-local-bundler/src/deploy/entrypoint.ts
Fixes #481
Some contracts included in our deployment script are expected to use the Arachnid CREATE deployment proxy instead of the Safe singleton factory. We change our deployment scripts to manually use the Arachnid CREATE2 deployer in those specific cases, so the contracts end up at the expected addresses.
Affected contracts:
- ERC-4337 entry point
- Daimo P-256 verifier
You can verify this works by running `pnpm run deploy hardhat` in the Passkey package and checking the deployment addresses are what you expect them to be:
```
...
deploying "EntryPoint" (tx: 0x58b5726a3381344205508251ec394b4bf74b6f8bc669be0b1c9de8d75ce1f8ef)...: deployed at 0x0000000071727De22E5E9d8BAf0edAc6f37da032 with 3650209 gas
...
deploying "DaimoP256Verifier" (tx: …
```
=> Use Arachnid CREATE2 Deployer For Some Contracts

modules/4337/contracts/Safe4337Module.sol
This PR adds a comment on dynamic signatures and signature length manipulation in `_checkSignaturesLength` Natspec
=> Add comment in _checkSignaturesLength regarding dynamic signatures

examples/4337-passkeys/.env.example, examples/4337-passkeys/package.json, examples/4337-passkeys/src/logic/userOp.ts, modules/passkey/package.json, modules/passkey/src/utils/webauthn.ts, modules/passkey/test/utils/webauthnShim.ts, modules/passkey/test/webauthn/WebAuthnShim.spec.ts, modules/passkey/tsconfig.json, packages/4337-local-bundler/docker-compose.yaml, pnpm-lock.yaml
When trying to solve https://github.com/safe-global/safe-modules/issues/395, I looked at the original error that triggered the discussion of adding an ESM build to the packages. I thought that the error was due to a bug in the bundler's ESM interoperability mechanism, but I realised that actually the issue was in the `cbor` package and compatibility with the browser environment.
When you import a js module, the code will get evaluated regardless of it use: https://www.perplexity.ai/search/does-javascript-evaluate-an-im-y4Zv1HKiQNmqxnHd1HJ1SA#0 (we may not use any of the functionality that's actually incompatible but because the code gets evaluated and it may imported a package that's unavailable in browser)
This PR:
- Fixes compatibility of the `@safe-global/safe-passkey` with the browser …
=> Update dependencies to use `cbor-web` instead of `cbor` in `@safe-global/safe-passkey` and update imports in the example app

modules/allowances/contracts/AllowanceModule.sol, modules/allowances/test/allowanceRecurring.spec.ts
This PR fixes a low severity audit finding by Ackee:
> It is possible to set the resetTimeMin to 0. When the resetBaseMin is bigger
than 0 and the resetTimeMin is 0, then the branch with modulo operation is
triggered and it will cause a division by zero. Since it is also in Solidity version
<0.8.0, it consumes all gas.
=> L-1: Add a reset period check to prevent the transaction failing and using all gas

modules/allowances/README.md, modules/allowances/hardhat.config.ts
- Add deployment instructions for contracts to README
- remove outdated networks from hardhat configuration
=> Allowance module: Add deployment instructions for contracts to README and remove outdated networks from hardhat configuration

modules/passkey/test/userstories/ExecuteSafeTransaction.spec.ts
This PR adds a "userstory" test that demonstrates how a passkey can be used to execute transactions directly on a Safe without going over ERC-4337.
It contains examples for both the shared signer, and signer factory.
=> Add Example of Passkey Executing Safe Transaction

modules/passkey/package.json, pnpm-lock.yaml
Fixes #510 
`@account-abstraction/contracts` is used only for testing in passkey module. The PR moves it to `devDependencies`
=> Move @account-abstraction/contracts to devDependencies in passkey module

modules/allowances/test/allowanceManagement.spec.ts, modules/allowances/test/allowanceSingle.spec.ts, modules/allowances/test/test-helpers/execAllowanceTransfer.ts, modules/allowances/test/test-helpers/setup.ts
Changes in PR:
- Add test cases to increase code coverage in `AllowanceModule` contract
- `SignatureDecoder` has in unused  internal function `recoverKey`. So, 100% code coverage for this contract is not possible.
=> Increase test coverage for AllowanceModule

modules/passkey/README.md
Fixes https://github.com/safe-global/safe-modules/issues/515.
Added a section on privacy regarding WebAuthn signatures and AAGUID which can be used to identify authenticator devices being used by users.
=> Add Privacy Section to README
