- allowances/.env.sample
- allowances/migrations/1_deploy_allowance_modules.js
- allowances/networks.json
- allowances/package.json
- allowances/scripts/generate_meta.js
- allowances/truffle-config.js
- allowances/yarn.lock
part of https://github.com/gnosis/safe-react-apps/issues/229
The PR:
- adds deployments to goerli and avalanche
- new environment variable to opt-in for https://github.com/gnosis/safe-singleton-factory
> Deploy to avalanche, polygon and goerli

- 4337/README.md
- 4337/contracts/EIP4337Module.sol
- 4337/contracts/test/SafeMock.sol
- 4337/contracts/test/TestEntryPoint.sol
- 4337/scripts/runOp.ts
- 4337/src/utils/safe.ts
- 4337/src/utils/userOp.ts
- 4337/test/eip4337/EIP4337ModuleExisting.spec.ts
- 4337/test/eip4337/EIP4337ModuleNew.spec.ts
- 4337/test/eip4337/EIP4337Safe.spec.ts
Closes #83:
- Adjust module to allow estimations
- Adjust script to be compatible with Pimlico
> Closes #83: Add integration tests

- 4337/contracts/EIP4337Module.sol
- 4337/scripts/runOp.ts
- 4337/src/deploy/deploy_eip4337.ts
- 4337/test/eip4337/EIP4337Module.spec.ts
- 4337/test/eip4337/EIP4337ModuleExisting.spec.ts
- 4337/test/eip4337/EIP4337ModuleNew.spec.ts
- 4337/test/eip4337/EIP4337Safe.spec.ts
- 4337/test/utils/setup.ts
This PR:
- Renames the module to `Safe4337Module`
> Rename Simple4337Module to Safe4337Module

- 4337/README.md
Update the sequence Diagram in the 4337 module README. In particular, this updates the execution flow, where the 4337 module acts as a module instead of the entry point acting as a module as it was previously depicted.
I also added the call data flow for when `execUserOpReturnData` is used.
> Update Sequence Diagram

- 4337/README.md
- 4337/test/eip4337/EIP4337ModuleExisting.spec.ts
- 4337/test/eip4337/EIP4337ModuleNew.spec.ts
This PR:
- Cleans up the readme of the 4337 module
- Fix grammar/spelling errors, rewrite some sentences for better clarity
> 4337 Module readme cleanup

- .github/workflows/cla.yml
This PR:
- https://github.com/safe-global/safe-modules/issues/119
Currently, it is missing the `CLA_ACCESS_TOKEN` environment variable. I have created an IT request asking them to set one.
> Feature: Add a cla action

- .github/workflows/cla.yml
The secret was renamed to `CLA_ACCESS_TOKEN`
> Fix CLA action secret name

- 4337/test/e2e/LocalBundler.spec.ts
This PR makes a small refactor to the E2E test to make it wait for user operation execution based on sender and nonce instead of side effects. This makes the tests more robust and (IMO at least) more self-explanatory.
> Refactor E2E Test to Wait For User Operation Execution

- 4337/package-lock.json
- 4337/package.json
This PR sets the NPM package version for the 4337 module to 0.2.0 in preparation for deploying the fixes implemented in #177.
> Package Version to v0.2.0

- modules/4337/contracts/experimental/SafeSignerLaunchpad.sol
While working on the WebAuthn PoC app, I got stuck with the gas estimation. After debugging, I discovered that the webauthn contract reverts if you provide an invalid signature. This goes against ERC-4337 specs:
> If the account does not support signature aggregation, it MUST validate the signature is a valid signature of the userOpHash, and SHOULD return SIG_VALIDATION_FAILED (and not revert) on signature mismatch. Any other error should revert.
This PR fixes it using a function similar to the `Safe4337Module`. No tests because experimental 😄
> Extract signature validation to a separate function in the launchpad contract

- package-lock.json
This PR solves the problem created due to the problem mentioned in https://github.com/npm/cli/issues/4828
We are rebuilding the lock files so it also works with Apple Silicon Macs.
> Rebuild `package-lock.json`

- modules/passkey/test/userStories/createSafeWithPasskeySignerAsOwner.ts
Fixes #275 
Changes in PR:
- Add a test case to showcase that a Safe can be deployed with Passkey signer as an owner
Tasks:
- Add test case
- Add comments
> User Story: 4337 account passkey owner

- packages/4337-local-bundler/src/deploy/safe.ts
`main` branch had a linting issue due to #337 which is resolved in this PR.
> Linting Issue Resolved

- modules/passkey/test/userStories/createSafeWithPasskeySignerAsOwner.ts
Related to #275.
Minor changes in PR:
- Remove unnecessary `wait()`
- change tag in test to `@userstory` for consistency
> Minor fix: Remove unnecessary wait(), change tag in test

- .gitignore
- examples/4337-passkeys/package.json
- examples/4337-passkeys/src/logic/passkeys.ts
- examples/4337-passkeys/src/logic/userOp.ts
- modules/passkey/contracts/4337/SafeECDSASignerLaunchpad.sol
- package-lock.json
This PR is a small step towards #360. What it does:
- Refactors the signing part with the passkey. I was rushing a bit when writing it and putting it directly in the `userOp.ts` file while a separate `passkeys.ts` file existed
- Adds `.idea` to the `.gitignore` file
- Upgrades all the dependencies for the app
- **(non-app refactor, I can move it to a separate PR if there are concerns)** Add comments to the `getInitHash` function in the launchpad contract
> Passkey example app: refactors and dependency upgrades

- modules/passkey/README.md
Fixes #293
Changes in PR:
- Document Safe Passkey deployment and execution flow.
> Document passkey signer flow

- modules/passkey/test/userstories/ExecuteWithPaymaster.spec.ts
Related to #276
This PR fixes import error in the user story merged in #357
> Fix imports in user story

- modules/passkey/README.md
- modules/passkey/contracts/SafeWebAuthnSignerFactory.sol
- modules/passkey/src/deploy/webauthn.ts
- modules/passkey/test/4337/WebAuthn.spec.ts
- modules/passkey/test/4337/WebAuthnSigner.spec.ts
- modules/passkey/test/GasBenchmarkingProxy.spec.ts
- modules/passkey/test/SafeWebAuthnSignerProxyFactory.spec.ts
- modules/passkey/test/userstories/CreateSafeWithPasskeySignerAsOwner.spec.ts
- modules/passkey/test/userstories/ExecuteUserOpFromPasskeySigner.spec.ts
- modules/passkey/test/userstories/ExecuteWithPaymaster.spec.ts
- modules/passkey/test/userstories/OffchainPasskeyVerification.spec.ts
- modules/passkey/test/userstories/PasskeyCredentialCreation.spec.ts
- modules/passkey/test/userstories/RotatePasskeyOwner.spec.ts
Fixes #381 
Changes in PR:
Do not merge.
> Document passkeys package

- examples/4337-passkeys/README.md
Fixes #345
Changes in PR:
- non-related: Fix a broken link to Passkey Signer contract
The broken link for which the issue was created has already been fixed.
> Update reference to Passkey code in README.md

- examples/4337-passkeys-singleton-signer/src/logic/safe.ts
- examples/4337-passkeys-singleton-signer/src/routes/DeploySafe.tsx
- examples/4337-passkeys-singleton-signer/src/routes/Home.tsx
- examples/4337-passkeys-singleton-signer/src/routes/Safe.tsx
This PR implements the optional part of https://github.com/safe-global/safe-modules/issues/400 (adding the connected eoa as a signer)
The OG PR: https://github.com/safe-global/safe-modules/pull/403
Demo: https://www.loom.com/share/ff30f1fbc4cc4d9cbe3a19035fa6cd18
> Example Singleton Webauthn Signer App: Include the connected eoa as a signer

- modules/passkey/test/4337/local-bundler/experimental/SafeWebAuthnSharedSigner.spec.ts
Fixes #372
This PR adds a new E2E test that demonstrates the use of a Safe being deployed over 4337 with multiple passkey owners. This means that we can have arbitrary ownership structures with passkeys and 4337 :tada:.
There is an important caveat however, the tracing mechanism used by the bundler is timing out when verifying multiple passkey signatures, so this E2E test is only half complete. At least we verify that the signature verification logic would work, and eventually when precompiles become part of Geth, we will be able to switch the E2E test to use that instead which should greatly speed up tracing.
I still think it is worth merging this PR as is, as it also checks that multiple shared signer instances can be used in parallel, a new feature added in #429.
> Add E2E Test For Multiple Passkey Owners With 4337

- examples/4337-passkeys/package.json
- pnpm-lock.yaml
This PR updates the passkey module version for the example with 4337.
> Passkey Version Update

- modules/passkey/CHANGELOG.md
- modules/passkey/README.md
- modules/passkey/docs/v0.2.0/audit.md
- modules/passkey/docs/v0.2.1/audit-competition-report-hats.md
- modules/passkey/docs/v0.2.1/audit.md
This PR adds the report from the audit competition to repository and updates the changelog to include the changes that were made as a result of the audit competition.
> Add Audit Competition Report

- modules/4337/certora/requirements.txt
Updating the version from `7.3.0` > `7.10.1`
> Upgrading certora CLI

- modules/recovery/README.md
We received a couple of questions about the documentation.
Added the link for clarity.
> Add link to Candidelabs documentation
